### ISSUE TITLE
How did you disable the TouchScreen?

### ISSUE THREAD

**Issue by galaxy-nomad** [opflep/T480s_Hackintosh#3]
I'm running a Lenovo Yoga 260 and would like to disable my touchscreen. Can you explain how you disabled the touchscreen on your setup?

UPDATE: I figured it out! For the Lenovo Yoga 260 you need to remove HS10 from your USBPorts.kext info.plist file. In your plist editor just do a search for "HS10" and delete that entry, save and restart your device and touchscreen will be disabled.

**Comment by opflep** [comment]
I used Hackintool to create a customized USBPort kext.

**Comment by galaxy-nomad** [comment]
Thank you I figured this out myself after ransacking the web. I just edited the info.plist of the USBPorts.kext in essence creating my own custom version of the kext. Of course the TouchScreen HS10 was the LAST HS value in the list so I had to go through all of them trial and error style to figure it out.🤣

**Comment by opflep** [comment]
> Thank you I figured this out myself after ransacking the web. I just edited the info.plist of the USBPorts.kext in essence creating my own custom version of the kext. Of course the TouchScreen HS10 was the LAST HS value in the list so I had to go through all of them trial and error style to figure it out.🤣

Congrats! Hard work paid off :)))
